# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e07e0a2aaad09a0435ca78b5d2c8ab945abd4c7e41030c5af2f6dcf4588dc7ad2e9fff87dfe041e1a07bad0fb8296ac3f23999c5986237cda92e2e315b661baf

test:
  secret_key_base: 2d34bbca3d1de20d04a7c6b54146e43b1eb2099cf31eedff011ba68b1c9afdc822c2ea83b0fc6a2bc640daafb9655f0daf91bb2eb65e92cb57dd9dac2358f981

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
